apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: config-loader
  name: config-loader
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: config-loader
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config-loader
    spec:
      containers:
      - image: jawlitkp/config-loader:v1.0.0
        env:
          - name: CONSUL_URL
            value: {{ .Values.consulIp }}
        imagePullPolicy: IfNotPresent
        name: config-loader
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
